- name: 创建mysql用户组
  group: name={{ mysql_user }}  state=present

- name: 创建mysql用户
  user: name={{ mysql_user }}  group={{ mysql_user }}  state=present create_home=False shell=/sbin/nologin

- name: 创建所需目录
  file: name={{ item }} state=directory mode=0755 recurse=yes
  with_items:
  - "{{ source_dir }}"
  - "{{ data_dir }}"

- name: 更改目录属主属组
  file: name={{ data_dir }} owner={{ mysql_user }} group={{ mysql_user }}

#当前主机下没有mysql包
#- name: 下载mysql包
#  get_url: url={{ download_url }} dest={{ source_dir }} owner={{ mysql_user }} group={{ mysql_user }} 

#当前主机file目录下已有mysql包
- name: 拷贝现有mysql包到所有主机
  copy: src={{ mysql_version }}-linux-glibc2.12-x86_64.tar.gz dest={{ source_dir }} owner={{ mysql_user }} group={{ mysql_user }}


- name: 解压mysql包
  unarchive: src={{ source_dir }}/{{ mysql_version }}-linux-glibc2.12-x86_64.tar.gz dest=/usr/local owner={{ mysql_user }} group={{ mysql_user }}

- name: 目录重命名
  shell: "mv /usr/local/mysql-5.7.25-linux-glibc2.12-x86_64 {{ base_dir }} && chown -R {{ mysql_user }}:{{ mysql_user }} {{ base_dir }}"

#复制数据库配置文件
- name: 拷贝mysql配置文件
  template: src=my.cnf dest=/etc/my.cnf owner=root group=root

#复制数据库服务文件
- name: 拷贝mysql服务文件
  template: src=mysqld.service dest=/usr/lib/systemd/system/mysqld.service owner=root group=root

#复制更改密码脚本
- name: 拷贝更改密码脚本
  template: src=change_passwd.sh dest={{ source_dir }} owner=root group=root

- name: 创建日志目录        
  file: name={{ item }} state=directory owner={{ mysql_user }} group={{ mysql_user }} mode=0755 recurse=yes
  with_items:
  - "/var/log/mysql"
  - "/var/run/mysqld"
  - "{{ base_dir }}/tmp"
  - "{{ base_dir }}/log"

- name: 创建错误日志文件
  file: dest={{ base_dir }}/log/error.log state=touch owner={{ mysql_user }} group={{ mysql_user }}
